# Generated by Django 5.0 on 2023-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("thumbnail", models.URLField()),
                ("flight_hour", models.IntegerField()),
                ("flag", models.URLField()),
            ],
        ),
    ]
