# Generated by Django 5.0 on 2023-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("theme", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="avg_flight_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="country",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="country",
            name="good_month",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="country",
            name="language",
            field=models.CharField(
                choices=[("kr", "Korean"), ("en", "English")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="country", name="rating", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="country",
            name="theme",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="country", name="name", field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name="country",
            name="spots",
            field=models.ManyToManyField(related_name="countries", to="countries.spot"),
        ),
    ]
