# Generated by Django 5.0 on 2023-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "countries",
            "0002_spot_country_avg_flight_price_country_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="avg_flight_price",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="country", name="description", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="good_month",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="rating",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="spots",
            field=models.ManyToManyField(
                null=True, related_name="countries", to="countries.spot"
            ),
        ),
    ]
