# Generated by Django 5.0 on 2023-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0003_alter_country_avg_flight_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="avg_flight_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="good_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("kr", "Korean"), ("en", "English"), ("cb", "Cebuano")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="rating",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="spots",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="countries", to="countries.spot"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="theme",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
