# Generated by Django 5.0 on 2023-12-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0004_alter_country_avg_flight_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("Korean", "kr"), ("English", "en"), ("Cebuano", "cb")],
                max_length=10,
                null=True,
            ),
        ),
    ]
