# Generated by Django 5.0 on 2023-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0005_alter_country_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
