# Generated by Django 5.0 on 2024-01-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_spot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, choices=[('Korean', 'kr'), ('English', 'en'), ('Cebuano', 'cb'), ('Vietnamese', 'vt'), ('Chinese', 'ch')], max_length=10, null=True),
        ),
    ]
