# Generated by Django 5.0 on 2023-12-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="file",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
